FROM jupyter/base-notebook:latest

USER root

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/

COPY requirements.txt .
RUN pip install -r requirements.txt