FROM python:3.9-slim

COPY . /app
WORKDIR /app

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean
    
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/
RUN pip install -r requirements.txt
ENTRYPOINT [ "streamlit", "run", "rcm_music_app.py"]